server {
  listen 19090;
  server_name _;

  location = /health {
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  location /connector/metrics {
    proxy_pass http://sag-connector:9103/metrics;
  }

  location /apisix/metrics {
    proxy_pass http://apisix:9091/apisix/prometheus/metrics;
  }

  location /mock/metrics {
    proxy_pass http://mock-workload:18080/metrics;
  }
}
