apisix:
  node_listen: 9080
  enable_admin: true
  enable_admin_cors: true

plugins:
  - prometheus

plugin_attr:
  prometheus:
    export_uri: /apisix/prometheus/metrics
    export_addr:
      ip: 0.0.0.0
      port: 9091
    metrics:
      http_status:
      http_latency:
      bandwidth:

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    allow_admin:
      - 0.0.0.0/0
    admin_key:
      - name: admin
        key: your-admin-key
        role: admin
  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30